// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYUc8T8i3h4T7bl_Feu1M4PGYNlLr2vi8',
    appId: '1:786152682081:ios:aa9fd03745efed7b193020',
    messagingSenderId: '786152682081',
    projectId: 'planet-aa60e',
    authDomain: 'planet-aa60e.firebaseapp.com',
    storageBucket: 'planet-aa60e.appspot.com',
    measurementId: 'G-DPP318DD1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbtzxkcZKFGdg2dinu63xE-Rb2FZRHdEw',
    appId: '1:786152682081:android:35d8c99dcb735f68193020',
    messagingSenderId: '786152682081',
    projectId: 'planet-aa60e',
    storageBucket: 'planet-aa60e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6WBHjE52hkTFisrAKhNqD7DUJAkslUxk',
    appId: '1:255313947969:ios:a3ef6eaa00f0fbe4be05c0',
    messagingSenderId: '786152682081',
    projectId: 'planet-aa60e',
    storageBucket: 'planet-aa60e.appspot.com',
    iosBundleId: 'Com.inetum.GoandGoCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6WBHjE52hkTFisrAKhNqD7DUJAkslUxk',
    appId: '1:255313947969:ios:7624a3c480753e99be05c0',
    messagingSenderId: '786152682081',
    projectId: 'planet-aa60e',
    storageBucket: 'planet-aa60e.appspot.com',
    iosBundleId: 'Com.inetum.GoandGoCar',
  );
}
